---
# 1. chrony 설치
- name: Install chrony
  ansible.builtin.dnf:
    name: chrony
    state: present

# 2. /etc/chrony.conf 배포
- name: Deploy /etc/chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    mode: '0644'
  notify: Restart Chrony

# 3. chronyd 서비스 활성화 및 시작
- name: Enable & start chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

# 4. firewalld 설치
- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present

# 5. firewalld 실행
- name: Ensure firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

# 6. NTP 포트 열기 (123/udp)
- name: Open firewall for NTP
  ansible.posix.firewalld:
    port: 123/udp
    permanent: true
    state: enabled
    immediate: true
    zone: public

# 7. 초기 동기화 (필요 시)
- name: Force initial step if large offset
  ansible.builtin.command: chronyc -a makestep
  changed_when: false
  failed_when: false
