---
# 1. MariaDB 서버 패키지 설치
- name: Install MariaDB server packages
  ansible.builtin.yum:
    name: "{{ db_packages }}"
    state: present
    
# 2. MariaDB 서비스 활성화 및 실행
- name: Ensure MariaDB service is running
  ansible.builtin.service:
    name: "{{ db_service }}"
    state: started
    enabled: yes

# 3. firewalld 설치 및 실행
- name: Ensure firewalld is installed
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

# 4. 방화벽에서 MySQL 포트 허용
- name: Open firewall for MySQL (MariaDB) port
  ansible.posix.firewalld:
    service: "{{ db_fw }}"
    permanent: yes
    state: enabled
    immediate: yes
