namespace: sonsejin
name: infra
version: 1.0.0
readme: README.md
authors:
  - "sonsejin <sonsejin@users.noreply.github.com>"
description: "Ansible roles for infra services (DNS, FTP, WEB, DB, MAIL, NTP)"
license: MIT
tags:
  - infra
  - dns
  - ftp
  - web
  - db
  - mail
  - ntp
dependencies: {}
repository: "https://github.com/sonsejin/myinfra"
documentation: "https://github.com/sonsejin/myinfra/blob/main/README.md"
homepage: "https://github.com/sonsejin/myinfra"
issues: "https://github.com/sonsejin/myinfra/issues"
