---
# web 서버 main.yml

- name: Install web package
  ansible.builtin.dnf:
    name: "{{ web_pkg }}"
    state: present

- name: Ensure web service is running
  ansible.builtin.systemd:
    name: "{{ web_service }}"
    state: started
    enabled: true

- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Open firewall for web
  ansible.posix.firewalld:
    service: "{{ web_fw }}"
    permanent: true
    immediate: true
    state: enabled
